apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: grass
  name: grass
spec:
  replicas: 3
  selector:
    matchLabels:
      app: grass
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: grass
    spec:
      containers:
      - image: httpd
        name: httpd
        resources: {}
status: {}
