apiVersion: apps/v1
kind: DaemonSet
metadata:
   name: mydaemon

spec:
  selector:
    matchLabels:
        app: myweb
  template:
    metadata:
       name: abc
       labels:
         app: myweb

    spec:
      containers:
        - name: xyz
          image: nginx

