apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydeployment-newdp
  
spec:
  replicas: 5
  selector:
     matchLabels:
        app: myweb
  template:
     metadata:
      labels:
        app: myweb
     spec:
       containers:
         - name: raj
           image: nginx
           ports:
             - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
   name: cipsvc
spec:
  selector:
    app: nginx

  ports:
    - targetPort: 80
      port: 80


