
apiVersion: v1
kind: Pod
metadata:
  name: my-pod
  labels:
    name: nginx
    app: webserver
spec:
  containers:
  - name: aary
    image: httpd:latest
    ports:
    - containerPort: 80
             
