apiVersion: v1
kind: ReplicationController
metadata:
   name: myapp

spec:
  replicas: 10
  selector:
    app: nginx
  template:
    metadata:
        name: my-pod
        labels:
          name: nginx
          app: nginx
    spec:
        containers:
            - name: container1
              image: httpd:latest
              ports: 
               - containerPort: 80     
