apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydb1
  
  
  
spec:
  replicas: 1
  selector:
     matchLabels:
        app: myweb
  template:
     metadata:
       name: mypod
       labels:
        app: myweb
     spec:
       containers:
         - name: mycontainer
           image: mysql
           envFrom:
             - configMapRef:
                   name: app-db
         
           volumeMounts:
                 - mountPath: /var/lib/mysql
                   name: xyz
       volumes:
             - name: xyz
               persistentVolumeClaim:
                       claimName: db-pvc

---
apiVersion: v1
kind: Service
metadata: 
   name: db-svc
   

spec:
  ports:
    - port: 3306
      protocol: TCP
      targetPort: 3306
  selector:
     app: myweb
