apiVersion: v1
kind: PersistentVolume
metadata:
   name: db-pv


spec:
   capacity:
        storage: 1G

   accessModes:
       - ReadWriteMany
   persistentVolumeReclaimPolicy: Retain
   nfs:
     server: 54.160.90.58 
     path: /nfs/database
   mountOptions:
     - hard 
