apiVersion: apps/v1
kind: Deployment
metadata:
  name: mywp
  namespace: mywebsite
  
  
spec:
  replicas: 10
  selector:
     matchLabels:
        app: mywp
  template:
     metadata:
       name: mypod
       labels:
        app: mywp
     spec:
       containers:
         - name: mycontainer2
           image: wordpress
           envFrom:
              - configMapRef:
                    name: app-wp1
    
           volumeMounts:
              - mountPath: /var/www/html
                name: pqr

       volumes:
         - name: pqr
           persistentVolumeClaim:
              claimName: wp1pvc


