apiVersion: v1
data:
  WORDPRESS_DB_HOST: 10.104.204.11
  WORDPRESS_DB_NAME: grras
  WORDPRESS_DB_PASSWORD: redhat
  WORDPRESS_DB_USER: root
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: app-wp1
  namespace: mywebsite
